schema_version = "1.0.0"

id         = "protein_runway"
version    = "0.0.1"
name       = "Protein Runway"
tagline    = "Render proteins with their trajectories, segment and extract normal modes."
maintainer = "Andrew Radev <contact@andrewra.dev>"

type    = "add-on"
website = "https://andrewradev.github.io/protein-runway/"
tags    = ["Animation", "Import-Export", "Physics"]

blender_version_min = "4.2.0"

# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "macos-arm64", "linux-x64", "macos-x64"]
# Other supported platforms: "windows-arm64"

# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
#
# All packages are dependencies of MDAnalysis
#
wheels = [
  "./wheels/GridDataFormats-1.0.2-py3-none-any.whl",
  "./wheels/MDAnalysis-2.8.0-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/MDAnalysis-2.8.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/MDAnalysis-2.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/MDAnalysis-2.8.0-cp311-cp311-win_amd64.whl",
  "./wheels/colorama-0.4.6-py2.py3-none-any.whl",
  "./wheels/contourpy-1.3.1-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/contourpy-1.3.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/contourpy-1.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/contourpy-1.3.1-cp311-cp311-win_amd64.whl",
  "./wheels/cycler-0.12.1-py3-none-any.whl",
  "./wheels/fasteners-0.19-py3-none-any.whl",
  "./wheels/fonttools-4.55.0-cp311-cp311-macosx_10_9_universal2.whl",
  "./wheels/fonttools-4.55.0-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/fonttools-4.55.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/fonttools-4.55.0-cp311-cp311-win_amd64.whl",
  "./wheels/joblib-1.4.2-py3-none-any.whl",
  "./wheels/kiwisolver-1.4.7-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/kiwisolver-1.4.7-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/kiwisolver-1.4.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/kiwisolver-1.4.7-cp311-cp311-win_amd64.whl",
  "./wheels/matplotlib-3.9.2-cp311-cp311-macosx_10_12_x86_64.whl",
  "./wheels/matplotlib-3.9.2-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/matplotlib-3.9.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/matplotlib-3.9.2-cp311-cp311-win_amd64.whl",
  "./wheels/mda_xdrlib-0.2.0-py3-none-any.whl",
  "./wheels/mdahole2-0.5.0-py3-none-any.whl",
  "./wheels/mmtf_python-1.1.3-py2.py3-none-any.whl",
  "./wheels/mrcfile-1.5.3-py2.py3-none-any.whl",
  "./wheels/msgpack-1.1.0-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/msgpack-1.1.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/msgpack-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/msgpack-1.1.0-cp311-cp311-win_amd64.whl",
  "./wheels/numpy-2.1.3-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/numpy-2.1.3-cp311-cp311-macosx_14_0_arm64.whl",
  "./wheels/numpy-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/numpy-2.1.3-cp311-cp311-win_amd64.whl",
  "./wheels/packaging-24.2-py3-none-any.whl",
  "./wheels/pathsimanalysis-1.2.0-py3-none-any.whl",
  "./wheels/pillow-11.0.0-cp311-cp311-macosx_10_10_x86_64.whl",
  "./wheels/pillow-11.0.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pillow-11.0.0-cp311-cp311-manylinux_2_28_x86_64.whl",
  "./wheels/pillow-11.0.0-cp311-cp311-win_amd64.whl",
  "./wheels/pyparsing-3.2.0-py3-none-any.whl",
  "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
  "./wheels/scipy-1.14.1-cp311-cp311-macosx_10_13_x86_64.whl",
  "./wheels/scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl",
  "./wheels/scipy-1.14.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/scipy-1.14.1-cp311-cp311-win_amd64.whl",
  "./wheels/six-1.16.0-py2.py3-none-any.whl",
  "./wheels/threadpoolctl-3.5.0-py3-none-any.whl",
  "./wheels/tqdm-4.67.1-py3-none-any.whl",
  "./wheels/waterdynamics-1.2.0-py3-none-any.whl",
]
