name: Build blender extension
on: [push]

jobs:
  build_blender_extension:
    name: Build blender extension on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Build and install wheels
        run: |
          cd blender/extension/
          pip wheel MDAnalysis -w wheels

      - name: Create zip file (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          cd blender/
          Compress-Archive `
            -Destination ../blender-extension-${{ runner.os }}_${{ runner.arch }}-${{ github.ref_name }}.zip `
            -Path extension/*

      - name: Create zip file (non-Windows)
        if: startsWith(matrix.os, 'windows') != true
        run: |
          cd blender
          zip -r \
            ../blender-extension-${{ runner.os }}_${{ runner.arch }}-${{ github.ref_name }}.zip \
            extension/*

      - name: Attach zip file to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            blender-extension-${{ runner.os }}_${{ runner.arch }}-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
