name: Run OOP tests

on: [push]

jobs:
  run_tests:
    name: Run all the tests located in the `/tests` directory
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: micromamba_env.yml
          cache-environment: true
          post-cleanup: 'none'

      - name: Install pip dependencies
        run: |
          micromamba run -n protein-runway pip install -r requirements.txt
          
      - name: Run segmentation parsers tests
        run: |
          micromamba run -n protein-runway python -m unittest tests/segmentation_parser_test.py

      - name: Run NMD trajectory tests
        run: |
          micromamba run -n protein-runway python -m unittest tests/generate_nmd_traj_test.py
