name: Run snakemake workflow
on: [push]

jobs:
  run_snakemake_workflow:
    name: Run snakemake workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: micromamba_env.yml
          cache-environment: true
          cache-environment-key: ${{ hashFiles('micromamba_env.yml') }}
          post-cleanup: 'none'

      - name: Install pip dependencies
        run: |
          micromamba run -n protein-runway pip install -r requirements.txt

      - name: Generate dag image artifact
        run: |
          micromamba run -n protein-runway snakemake --dag 03_output/5vde_example.segmentation.tsv | micromamba run -n protein-runway dot -Tsvg > dag.svg
      - uses: actions/upload-artifact@v4
        with:
            name: dag-image
            path: dag.svg

      - name: Generate filegraph image artifact
        run: |
          micromamba run -n protein-runway snakemake --filegraph 03_output/5vde_example.segmentation.tsv | micromamba run -n protein-runway dot -Tsvg > filegraph.svg
      - uses: actions/upload-artifact@v4
        with:
            name: filegraph-image
            path: filegraph.svg

      - name: Run snakemake
        run: |
          micromamba run -n protein-runway snakemake

      
