name: Run snakemake workflow
on: [push]

jobs:
  run_snakemake_workflow:
    name: Run snakemake workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: micromamba_env.yml
          cache-environment: true
          cache-environment-key: ${{ hashFiles('micromamba_env.yml') }}
          post-cleanup: 'none'

      - name: Install pip dependencies
        run: |
          micromamba run -n protein-runway pip install -r requirements.txt

      - name: Generate image artifacts
        run: |
          micromamba run -n protein-runway bash scripts/generate_snakemake_graphs.sh 5vde_example

      - uses: actions/upload-artifact@v4
        with:
          name: workflow-graphs
          path: '04_extra/graphs/*.svg'

      - name: Run snakemake
        run: |
          micromamba run -n protein-runway snakemake
