name: Run snakemake workflow

on: [push]

jobs:
  run_snakemake_workflow:
    name: Build the entire workflow with the example inputs in git
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: micromamba_env.yml
          cache-environment: true
          post-cleanup: 'none'

      - name: Install pip dependencies
        run: |
          micromamba run -n protein-runway pip install -r requirements.txt

      - name: Run library tests
        run: |
          micromamba run -n protein-runway python tests/*.py

      - name: Run blender tests
        run: |
          cd blender/extension/
          micromamba run -n protein-runway python tests/*.py
